#!/bin/bash
jalv -i http://eseris.fr/lv2/mushroom &
sleep 0.1
jack_connect 'Ese Champignon:out' 'PulseAudio JACK Source:front-left'
jack_connect 'Ese Champignon:out' 'PulseAudio JACK Source:front-right'
wait
